import Foundation

// MARK: - iTerm2

/// iTerm2 watches ~/Library/Application Support/iTerm2/DynamicProfiles and
/// picks up changes live, so a theme switch is a file write. The user selects
/// the Omakase profile once; after that every switch follows it.
public struct ITerm2Integration: Integration {
    public let id = "iterm2", name = "iTerm2"
    public init() {}

    /// Stable so we keep updating the same profile instead of piling up new ones.
    static let guid = "4F0F2A57-0F3A-4B5C-9B0C-0E1D2C3B4A59"

    var profile: URL {
        Files.home.appendingPathComponent(
            "Library/Application Support/iTerm2/DynamicProfiles/omakase.json")
    }

    public var isInstalled: Bool {
        Files.exists(URL(fileURLWithPath: "/Applications/iTerm.app"))
            || Files.exists(Files.home.appendingPathComponent("Applications/iTerm.app"))
    }
    public var isWired: Bool { Files.exists(profile) }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        func component(_ c: Color) -> [String: Any] {
            ["Red Component": Double(c.r) / 255,
             "Green Component": Double(c.g) / 255,
             "Blue Component": Double(c.b) / 255,
             "Alpha Component": 1,
             "Color Space": "sRGB"]
        }
        var p: [String: Any] = [
            "Name": "Omakase",
            "Guid": Self.guid,
            "Background Color": component(theme.background),
            "Foreground Color": component(theme.foreground),
            "Cursor Color": component(theme.cursor),
            "Cursor Text Color": component(theme.background),
            "Selection Color": component(theme.selectionBackground),
            "Selected Text Color": component(theme.selectionForeground),
            "Bold Color": component(theme.foreground),
        ]
        for (i, c) in theme.palette.enumerated() { p["Ansi \(i) Color"] = component(c) }

        let data = try JSONSerialization.data(withJSONObject: ["Profiles": [p]],
                                              options: [.prettyPrinted, .sortedKeys])
        try FileManager.default.createDirectory(
            at: profile.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: profile)
        return nil
    }
}

// MARK: - Alacritty

public struct AlacrittyIntegration: Integration {
    public let id = "alacritty", name = "Alacritty"
    public init() {}

    var userConfig: URL { Files.config("alacritty/alacritty.toml") }
    func generated(_ l: Library) -> URL { l.generated.appendingPathComponent("alacritty.toml") }

    public var isInstalled: Bool {
        Shell.which("alacritty") != nil
            || Files.exists(URL(fileURLWithPath: "/Applications/Alacritty.app"))
    }
    public var isWired: Bool {
        Files.references(Library().generated.appendingPathComponent("alacritty.toml"),
                         in: userConfig)
    }

    /// `import` moved under [general] in 0.14, and the old top-level form warns.
    /// Ask the binary which one it wants rather than guessing.
    var usesGeneralSection: Bool {
        guard let bin = Shell.which("alacritty") else { return true }
        let version = Shell.run(bin, ["--version"], timeout: 5).out
        guard let match = version.split(separator: " ").dropFirst().first,
              let minor = match.split(separator: ".").dropFirst().first,
              let n = Int(minor) else { return true }
        return n >= 14
    }

    public func install(_ l: Library) throws {
        guard isInstalled, !isWired else { return }
        Files.backup(userConfig)
        let body = Files.read(userConfig) ?? ""
        let line = usesGeneralSection
            ? "\n# omakase\n[general]\nimport = [\"\(generated(l).path)\"]\n"
            : "\n# omakase\nimport = [\"\(generated(l).path)\"]\n"
        try Files.write(body + line, to: userConfig)
    }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        func list(_ range: Range<Int>) -> String {
            let names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
            return zip(names, range.map { theme.palette[$0] })
                .map { "\($0) = \"\($1.hex)\"" }
                .joined(separator: "\n")
        }
        // Alacritty reloads its config on write, so no signal is needed.
        try Files.write("""
        # Generated by omakase — do not edit by hand.
        # Theme: \(theme.name)

        [colors.primary]
        background = "\(theme.background.hex)"
        foreground = "\(theme.foreground.hex)"

        [colors.cursor]
        cursor = "\(theme.cursor.hex)"
        text = "\(theme.background.hex)"

        [colors.selection]
        background = "\(theme.selectionBackground.hex)"
        text = "\(theme.selectionForeground.hex)"

        [colors.normal]
        \(list(0..<8))

        [colors.bright]
        \(list(8..<16))

        """, to: generated(l))
        return nil
    }
}

// MARK: - kitty

public struct KittyIntegration: Integration {
    public let id = "kitty", name = "kitty"
    public init() {}

    var userConfig: URL { Files.config("kitty/kitty.conf") }
    func generated(_ l: Library) -> URL { l.generated.appendingPathComponent("kitty.conf") }

    public var isInstalled: Bool {
        Shell.which("kitty") != nil
            || Files.exists(URL(fileURLWithPath: "/Applications/kitty.app"))
    }
    public var isWired: Bool {
        Files.references(Library().generated.appendingPathComponent("kitty.conf"), in: userConfig)
    }

    public func install(_ l: Library) throws {
        guard isInstalled, !isWired else { return }
        Files.backup(userConfig)
        let body = Files.read(userConfig) ?? ""
        let sep = body.isEmpty || body.hasSuffix("\n") ? "" : "\n"
        try Files.write("\(body)\(sep)\n# omakase\ninclude \(generated(l).path)\n", to: userConfig)
    }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        var lines = ["# Generated by omakase — do not edit by hand.",
                     "# Theme: \(theme.name)", "",
                     "background \(theme.background.hex)",
                     "foreground \(theme.foreground.hex)",
                     "cursor \(theme.cursor.hex)",
                     "cursor_text_color \(theme.background.hex)",
                     "selection_background \(theme.selectionBackground.hex)",
                     "selection_foreground \(theme.selectionForeground.hex)", ""]
        for (i, c) in theme.palette.enumerated() { lines.append("color\(i) \(c.hex)") }
        try Files.write(lines.joined(separator: "\n") + "\n", to: generated(l))

        // Same trick as Ghostty: SIGUSR1 reloads kitty's config in place.
        for pid in Shell.pids(of: "kitty") { kill(pid, SIGUSR1) }
        return nil
    }
}

// MARK: - WezTerm

public struct WezTermIntegration: Integration {
    public let id = "wezterm", name = "WezTerm"
    public init() {}

    var scheme: URL { Files.config("wezterm/colors/omakase.toml") }
    var userConfig: URL { Files.config("wezterm/wezterm.lua") }

    public var isInstalled: Bool {
        Shell.which("wezterm") != nil
            || Files.exists(URL(fileURLWithPath: "/Applications/WezTerm.app"))
    }
    public var isWired: Bool {
        (Files.read(userConfig) ?? "").contains("Omakase")
    }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        func list(_ range: Range<Int>) -> String {
            range.map { "\"\(theme.palette[$0].hex)\"" }.joined(separator: ", ")
        }
        // WezTerm watches its config directory and reloads on its own.
        try Files.write("""
        # Generated by omakase — do not edit by hand.
        [metadata]
        name = "Omakase"

        [colors]
        foreground = "\(theme.foreground.hex)"
        background = "\(theme.background.hex)"
        cursor_bg = "\(theme.cursor.hex)"
        cursor_fg = "\(theme.background.hex)"
        cursor_border = "\(theme.cursor.hex)"
        selection_fg = "\(theme.selectionForeground.hex)"
        selection_bg = "\(theme.selectionBackground.hex)"
        ansi = [\(list(0..<8))]
        brights = [\(list(8..<16))]

        """, to: scheme)

        return isWired ? nil
            : "WezTerm: add `config.color_scheme = 'Omakase'` to wezterm.lua"
    }
}
