import Foundation

/// herdr renders its own tab bar and side panel with its own theming engine and
/// inherits nothing from the terminal, so without this a dark theme leaves a
/// light bar sitting on top of it.
///
/// The edit is surgical: only the [theme.custom] block and the `name` line in
/// [theme] are rewritten, and the rest of the user's config — comments included
/// — is preserved.
public struct HerdrIntegration: Integration {
    public let id = "herdr", name = "herdr"
    public init() {}

    var config: URL { Files.config("herdr/config.toml") }

    public var isInstalled: Bool { Shell.which("herdr") != nil || Files.exists(config) }
    public var isWired: Bool { (Files.read(config) ?? "").contains("[theme.custom]") }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        guard let original = Files.read(config) else { return nil }
        let bg = theme.background, fg = theme.foreground, p = theme.palette

        // Field names follow Catppuccin's, which is what herdr expects.
        let colors: [(String, Color)] = [
            ("accent", theme.accent), ("panel_bg", bg),
            ("surface_dim", bg.mixed(with: fg, 0.05)),
            ("surface0", bg.mixed(with: fg, 0.08)),
            ("surface1", bg.mixed(with: fg, 0.14)),
            ("overlay0", bg.mixed(with: fg, 0.40)),
            ("overlay1", bg.mixed(with: fg, 0.55)),
            ("text", fg), ("subtext0", bg.mixed(with: fg, 0.65)),
            ("mauve", p[5]), ("green", p[2]), ("yellow", p[3]), ("red", p[1]),
            ("blue", p[4]), ("teal", p[6]), ("peach", p[9]),
        ]
        // A base of the right lightness, so anything custom does not cover stays
        // coherent.
        let base = theme.appearance == .dark ? "rose-pine" : "rose-pine-dawn"

        Files.backup(config)
        var out: [String] = []
        var inTheme = false
        var lines = original.split(separator: "\n", omittingEmptySubsequences: false)
            .map(String.init)
        var i = 0
        while i < lines.count {
            let line = lines[i]
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed == "[theme.custom]" {          // drop the old block whole
                i += 1
                while i < lines.count,
                      !lines[i].trimmingCharacters(in: .whitespaces).hasPrefix("[") { i += 1 }
                continue
            }
            if trimmed.hasPrefix("[") {
                inTheme = trimmed == "[theme]"
            } else if inTheme, trimmed.hasPrefix("name") , trimmed.contains("=") {
                out.append("name = \"\(base)\"")
                i += 1
                continue
            }
            out.append(line)
            i += 1
        }
        while let last = out.last, last.trimmingCharacters(in: .whitespaces).isEmpty {
            out.removeLast()
        }
        out.append("")
        out.append("# Generated by omakase — do not edit by hand.")
        out.append("[theme.custom]")
        out.append(contentsOf: colors.map { "\($0.0) = \"\($0.1.hex)\"" })
        try Files.write(out.joined(separator: "\n") + "\n", to: config)

        // Reloads over its socket, without losing the session.
        if let bin = Shell.which("herdr"), Shell.isRunning("herdr") {
            let r = Shell.run(bin, ["server", "reload-config"])
            if r.status != 0 || !r.out.contains("\"status\":\"applied\"") {
                return "herdr: config written, but the reload failed (restart herdr to see it)"
            }
        }
        return nil
    }
}
