import Foundation

// MARK: - Ghostty

public struct GhosttyIntegration: Integration {
    public let id = "ghostty", name = "Ghostty"
    public let machine: Machine
    public init(machine: Machine = .current) { self.machine = machine }

    var userConfig: URL { machine.config("ghostty/config") }
    func generated(_ l: Library) -> URL { l.generated.appendingPathComponent("ghostty.conf") }

    public var isInstalled: Bool {
        Files.exists(URL(fileURLWithPath: "/Applications/Ghostty.app"))
            || Shell.which("ghostty") != nil
    }
    public func isWired(_ l: Library) -> Bool {
        Files.references(l.generated.appendingPathComponent("ghostty.conf"), in: userConfig)
    }

    public func install(_ l: Library) throws {
        guard isInstalled, !isWired(l) else { return }
        Files.backup(userConfig)
        let body = Files.read(userConfig) ?? ""
        let sep = body.isEmpty || body.hasSuffix("\n") ? "" : "\n"
        try Files.write(body + sep + "\n# omakase\nconfig-file = ?\(generated(l).path)\n",
                        to: userConfig)
    }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        var lines = ["# Generated by omakase — do not edit by hand.",
                     "# Theme: \(theme.name)", ""]
        for (i, c) in theme.palette.enumerated() { lines.append("palette = \(i)=\(c.hex)") }
        lines += ["",
                  "background = \(theme.background.hex)",
                  "foreground = \(theme.foreground.hex)",
                  "cursor-color = \(theme.cursor.hex)",
                  "cursor-text = \(theme.background.hex)",
                  "selection-background = \(theme.selectionBackground.hex)",
                  "selection-foreground = \(theme.selectionForeground.hex)",
                  "window-theme = \(theme.appearance.rawValue)", ""]
        try Files.write(lines.joined(separator: "\n"), to: generated(l))

        // SIGUSR2 reloads every open surface without stealing focus or needing
        // any permission. The process is "ghostty", lowercase.
        guard machine.appliesLive else { return nil }
        for pid in Shell.pids(of: "ghostty") { kill(pid, SIGUSR2) }
        return nil
    }
}

// MARK: - SketchyBar

public struct SketchyBarIntegration: Integration {
    public let id = "sketchybar", name = "SketchyBar"
    public let machine: Machine
    public init(machine: Machine = .current) { self.machine = machine }

    var shim: URL { machine.config("sketchybar/colors.sh") }
    func generated(_ l: Library) -> URL { l.generated.appendingPathComponent("sketchybar-colors.sh") }

    public var isInstalled: Bool { Shell.which("sketchybar") != nil }
    public func isWired(_ l: Library) -> Bool {
        Files.references(l.generated.appendingPathComponent("sketchybar-colors.sh"), in: shim)
    }

    public func install(_ l: Library) throws {
        guard isInstalled, !isWired(l) else { return }
        Files.backup(shim)
        try Files.write("""
        #!/bin/bash
        # Shim written by omakase — the colours live in the active theme.
        source "\(generated(l).path)"
        """, to: shim, executable: true)
    }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        let bg = theme.background, fg = theme.foreground, accent = theme.accent
        let border = bg.mixed(with: fg, 0.16)
        let onAccent = accent.luma > 0.55 ? Color(r: 17, g: 17, b: 17) : Color(r: 255, g: 255, b: 255)
        func q(_ s: String) -> String { "'\(s)'" }   // values are hex; quoted anyway

        try Files.write("""
        #!/bin/bash
        # Generated by omakase — do not edit by hand.
        # Theme: \(theme.name)
        # SketchyBar format: 0xAARRGGBB (alpha comes FIRST).

        export BAR_COLOR=\(q(bg.sketchybar(alpha: 0xf0)))
        export BAR_BORDER_COLOR=\(q(border.sketchybar()))
        export ITEM_BG_COLOR=\(q(bg.mixed(with: fg, 0.08).sketchybar()))
        export ITEM_BORDER_COLOR=\(q(border.sketchybar()))

        export FG=\(q(fg.sketchybar()))
        export FG_DIM=\(q(bg.mixed(with: fg, 0.60).sketchybar()))
        export FG_ON_ACCENT=\(q(onAccent.sketchybar()))

        export ACCENT=\(q(accent.sketchybar()))
        export BLUE=\(q(theme.palette[4].sketchybar()))
        export PURPLE=\(q(theme.palette[5].sketchybar()))
        export GREEN=\(q(theme.palette[2].sketchybar()))
        export RED=\(q(theme.palette[1].sketchybar()))
        export ORANGE=\(q(theme.palette[11].sketchybar()))
        export YELLOW=\(q(theme.palette[3].sketchybar()))
        export CYAN=\(q(theme.palette[6].sketchybar()))
        export MAGENTA=\(q(theme.palette[13].sketchybar()))

        export WS_FOCUSED_BG=\(q(accent.sketchybar()))
        export WS_FOCUSED_FG=\(q(onAccent.sketchybar()))
        export WS_VISIBLE_BG=\(q(accent.sketchybar(alpha: 0x40)))
        export WS_VISIBLE_FG=\(q(accent.sketchybar()))
        export WS_OCCUPIED_BG='0x00000000'
        export WS_OCCUPIED_FG=\(q(fg.sketchybar()))
        export WS_EMPTY_FG=\(q(bg.mixed(with: fg, 0.60).sketchybar()))

        export TRANSPARENT='0x00000000'

        """, to: generated(l))

        if machine.appliesLive, let bin = Shell.which("sketchybar"), Shell.isRunning("sketchybar") {
            Shell.run(bin, ["--reload"])
        }
        return nil
    }
}

// MARK: - JankyBorders

public struct BordersIntegration: Integration {
    public let id = "borders", name = "JankyBorders"
    public let machine: Machine
    public init(machine: Machine = .current) { self.machine = machine }

    var rc: URL { machine.config("borders/bordersrc") }
    public var isInstalled: Bool { Shell.which("borders") != nil }
    public func isWired(_ l: Library) -> Bool { Files.exists(rc) }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        guard let bin = Shell.which("borders") else { return nil }
        // Absolute path on purpose: a window manager launches this without the
        // user's PATH.
        try Files.write("""
        #!/bin/bash
        # Generated by omakase — do not edit by hand.
        # Theme: \(theme.name)
        options=(
          'active_color=0xff\(theme.accent.bare)'
          'inactive_color=0x00000000'
          'width=6.0'
        )
        exec \(bin) "${options[@]}"

        """, to: rc, executable: true)

        guard machine.appliesLive else { return nil }
        Shell.run("/usr/bin/pkill", ["-x", "borders"], timeout: 5)
        let p = Process()
        p.executableURL = rc
        try? p.run()
        return nil
    }
}

// MARK: - System appearance

public struct AppearanceIntegration: Integration {
    public let id = "appearance", name = "Light/dark mode"
    public let machine: Machine
    public init(machine: Machine = .current) { self.machine = machine }
    public var isInstalled: Bool { true }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        guard machine.appliesLive else { return nil }
        let dark = theme.appearance == .dark
        let rc = Shell.osascript("""
        tell application "System Events" to tell appearance preferences \
        to set dark mode to \(dark)
        """)
        return rc == 0 ? nil : "light/dark mode needs Automation permission for System Events"
    }
}

// MARK: - Wallpaper

public struct WallpaperIntegration: Integration {
    public let id = "wallpaper", name = "Desktop wallpaper"
    public let machine: Machine
    public init(machine: Machine = .current) { self.machine = machine }
    public var isInstalled: Bool { true }

    var index: URL {
        machine.library("Application Support/com.apple.wallpaper/Store/Index.plist")
    }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        guard machine.appliesLive else { return nil }
        if let image = l.wallpaper(for: theme) { return set(image) }

        // No picture yet. If one is on its way — the theme knows where it came
        // from — put the theme's own colour up immediately rather than leaving
        // the previous wallpaper sitting there while everything else changed.
        // A theme that ships none at all still leaves the desktop alone, on
        // purpose: a dynamic system wallpaper has no file path to restore.
        let source = theme.directory.appendingPathComponent("source.json")
        guard FileManager.default.fileExists(atPath: source.path),
              let flat = SolidImage.url(for: theme.background, in: l) else { return nil }
        return set(flat)
    }

    /// Apply to EVERY Space and display.
    ///
    /// AppleScript's `tell every desktop to set picture` only reaches the
    /// active Space of each display, so every other Mission Control Space keeps
    /// the old picture. The only way to cover them all is to rewrite
    /// WallpaperAgent's index and restart it.
    @discardableResult
    public func set(_ image: URL) -> String? {
        guard Files.exists(index) else {
            let rc = Shell.osascript("""
            tell application "System Events" to tell every desktop \
            to set picture to POSIX file \(Shell.applescriptString(image.path))
            """)
            return rc == 0 ? nil : "wallpaper: not applied"
        }
        Files.backup(index)
        guard let data = try? Data(contentsOf: index),
              let plist = try? PropertyListSerialization.propertyList(
                from: data, options: [.mutableContainersAndLeaves], format: nil)
        else { return "wallpaper: could not read the index" }

        let configuration = try? PropertyListSerialization.data(
            fromPropertyList: ["type": "imageFile",
                               "url": ["relative": image.absoluteString]],
            format: .binary, options: 0)
        guard let configuration else { return "wallpaper: could not encode the choice" }

        let changed = Self.retarget(plist as AnyObject, with: configuration)
        guard changed > 0 else { return "wallpaper: no image entry to repoint" }
        guard let out = try? PropertyListSerialization.data(
            fromPropertyList: plist, format: .binary, options: 0),
              (try? out.write(to: index)) != nil
        else { return "wallpaper: could not write the index" }

        Shell.run("/usr/bin/killall", ["WallpaperAgent"], timeout: 5)
        return nil
    }

    /// Repoint every image choice, at any depth.
    static func retarget(_ node: AnyObject, with configuration: Data) -> Int {
        if let dict = node as? NSMutableDictionary {
            if dict["Provider"] as? String == "com.apple.wallpaper.choice.image" {
                dict["Configuration"] = configuration
                return 1
            }
            return dict.allValues.reduce(0) { $0 + retarget($1 as AnyObject, with: configuration) }
        }
        if let array = node as? NSMutableArray {
            return array.reduce(0) { $0 + retarget($1 as AnyObject, with: configuration) }
        }
        return 0
    }
}
