import Foundation

// MARK: - btop

public struct BtopIntegration: Integration {
    public let id = "btop", name = "btop"
    public let machine: Machine
    public init(machine: Machine = .current) { self.machine = machine }

    var themeFile: URL { machine.config("btop/themes/artheme.theme") }
    var conf: URL { machine.config("btop/btop.conf") }

    public var isInstalled: Bool { Shell.which("btop") != nil }
    public func isWired(_ l: Library) -> Bool { (Files.read(conf) ?? "").contains("\"artheme\"") }

    public func install(_ l: Library) throws {
        guard isInstalled, !isWired(l) else { return }
        Files.backup(conf)
        var body = Files.read(conf) ?? ""
        // btop.conf is plain key = "value": replace the line if it is there,
        // append it if it is not. Everything else is left untouched.
        if body.contains("color_theme") {
            body = body.split(separator: "\n", omittingEmptySubsequences: false)
                .map { $0.hasPrefix("color_theme") ? "color_theme = \"artheme\"" : String($0) }
                .joined(separator: "\n")
        } else {
            body += (body.hasSuffix("\n") || body.isEmpty ? "" : "\n") + "color_theme = \"artheme\"\n"
        }
        try Files.write(body, to: conf)
    }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        let bg = theme.background, fg = theme.foreground, p = theme.palette
        let dim = bg.mixed(with: fg, 0.45)
        // btop reads themes only at startup; a running instance keeps its colours.
        try Files.write("""
        # Generated by artheme — do not edit by hand.
        # Theme: \(theme.name)
        theme[main_bg]="\(bg.hex)"
        theme[main_fg]="\(fg.hex)"
        theme[title]="\(fg.hex)"
        theme[hi_fg]="\(theme.accent.hex)"
        theme[selected_bg]="\(theme.selectionBackground.hex)"
        theme[selected_fg]="\(theme.selectionForeground.hex)"
        theme[inactive_fg]="\(dim.hex)"
        theme[graph_text]="\(dim.hex)"
        theme[meter_bg]="\(bg.mixed(with: fg, 0.20).hex)"
        theme[proc_misc]="\(p[6].hex)"
        theme[cpu_box]="\(bg.mixed(with: fg, 0.30).hex)"
        theme[mem_box]="\(bg.mixed(with: fg, 0.30).hex)"
        theme[net_box]="\(bg.mixed(with: fg, 0.30).hex)"
        theme[proc_box]="\(bg.mixed(with: fg, 0.30).hex)"
        theme[div_line]="\(bg.mixed(with: fg, 0.20).hex)"
        theme[temp_start]="\(p[2].hex)"
        theme[temp_mid]="\(p[3].hex)"
        theme[temp_end]="\(p[1].hex)"
        theme[cpu_start]="\(p[6].hex)"
        theme[cpu_mid]="\(p[4].hex)"
        theme[cpu_end]="\(p[5].hex)"
        theme[free_start]="\(p[2].hex)"
        theme[free_mid]="\(p[10].hex)"
        theme[free_end]="\(p[2].hex)"
        theme[cached_start]="\(p[6].hex)"
        theme[cached_mid]="\(p[14].hex)"
        theme[cached_end]="\(p[6].hex)"
        theme[available_start]="\(p[3].hex)"
        theme[available_mid]="\(p[11].hex)"
        theme[available_end]="\(p[3].hex)"
        theme[used_start]="\(p[1].hex)"
        theme[used_mid]="\(p[9].hex)"
        theme[used_end]="\(p[1].hex)"
        theme[download_start]="\(p[4].hex)"
        theme[download_mid]="\(p[12].hex)"
        theme[download_end]="\(p[4].hex)"
        theme[upload_start]="\(p[5].hex)"
        theme[upload_mid]="\(p[13].hex)"
        theme[upload_end]="\(p[5].hex)"
        theme[process_start]="\(p[4].hex)"
        theme[process_mid]="\(p[5].hex)"
        theme[process_end]="\(p[1].hex)"

        """, to: themeFile)
        return nil
    }
}

// MARK: - tmux

public struct TmuxIntegration: Integration {
    public let id = "tmux", name = "tmux"
    public let machine: Machine
    public init(machine: Machine = .current) { self.machine = machine }

    func generated(_ l: Library) -> URL { l.generated.appendingPathComponent("tmux.conf") }
    /// tmux reads ~/.config/tmux/tmux.conf on 3.1+, and ~/.tmux.conf before that.
    var userConfig: URL {
        let xdg = machine.config("tmux/tmux.conf")
        if Files.exists(xdg) { return xdg }
        let legacy = machine.home.appendingPathComponent(".tmux.conf")
        return Files.exists(legacy) ? legacy : xdg
    }

    public var isInstalled: Bool { Shell.which("tmux") != nil }
    public func isWired(_ l: Library) -> Bool {
        Files.references(l.generated.appendingPathComponent("tmux.conf"), in: userConfig)
    }

    public func install(_ l: Library) throws {
        guard isInstalled, !isWired(l) else { return }
        Files.backup(userConfig)
        let body = Files.read(userConfig) ?? ""
        let sep = body.isEmpty || body.hasSuffix("\n") ? "" : "\n"
        try Files.write("\(body)\(sep)\n# artheme\nsource-file \(generated(l).path)\n",
                        to: userConfig)
    }

    public func apply(_ theme: Theme, _ l: Library) throws -> String? {
        let bg = theme.background, fg = theme.foreground, accent = theme.accent
        let panel = bg.mixed(with: fg, 0.10)
        let dim = bg.mixed(with: fg, 0.55)
        let onAccent = accent.luma > 0.55 ? "#111111" : "#ffffff"
        try Files.write("""
        # Generated by artheme — do not edit by hand.
        # Theme: \(theme.name)
        set -g status-style "bg=\(panel.hex),fg=\(fg.hex)"
        set -g status-left-style "bg=\(accent.hex),fg=\(onAccent)"
        set -g status-right-style "bg=\(panel.hex),fg=\(dim.hex)"
        set -g window-status-current-style "bg=\(accent.hex),fg=\(onAccent),bold"
        set -g window-status-style "bg=\(panel.hex),fg=\(dim.hex)"
        set -g pane-border-style "fg=\(bg.mixed(with: fg, 0.20).hex)"
        set -g pane-active-border-style "fg=\(accent.hex)"
        set -g message-style "bg=\(accent.hex),fg=\(onAccent)"
        set -g mode-style "bg=\(theme.selectionBackground.hex),fg=\(theme.selectionForeground.hex)"
        set -g display-panes-active-colour "\(accent.hex)"
        set -g display-panes-colour "\(dim.hex)"
        set -g clock-mode-colour "\(accent.hex)"

        """, to: generated(l))

        // Live reload, if a server is running: the panes repaint immediately.
        if machine.appliesLive, let bin = Shell.which("tmux"), Shell.isRunning("tmux") {
            Shell.run(bin, ["source-file", generated(l).path], timeout: 5)
        }
        return nil
    }
}
